services:
  fastapi:
    build:
      context: .
    container_name: fastapi_app_runner
    expose:
      - "8000"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi